spring:
  datasource:
    url: jdbc:postgresql://${DB_IP}:{DB_PORT}/postgres
    username: postgres
    password: {DB_PASSWORD}
  jpa:
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: serat5915@gmail.com
    password: ${EMAIL_SERVICE_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  servlet:
    context-path: /farmer-market-api
  port: 8989

app:
  auth:
    jwt:
      public-key: secret-key
      expiration-ms: 1800000

logging:
  level:
    org:
      springframework:
        security: DEBUG